apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}-db
spec:
    type: NodePort
    ports: 
    - name: db
      port: 30033
      targetPort: 5432 # Docker 暴露出来的接口
    selector:
      app: {{ .Values.name }} 