apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}{{ .Values.USERID }}-service
spec:
  type: NodePort
  ports:
    - name: {{ .Values.service.ssh.name }}
      port: {{ .Values.service.ssh.port }} 
      targetPort: {{ .Values.service.ssh.targetPort }} 
  selector:
    app: {{ .Values.name }}{{ .Values.USERID }}