apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}-ssh
spec:
    type: NodePort
    ports:
    - name: ssh
      port: 30034
      targetPort: 22 # Docker 暴露出来的接口
    selector:
      app: {{ .Values.name }}  }