apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}-service
spec:
    type: NodePort
    ports:
    - name: {{ .Values.service.ssh.name }}
      port: {{ .Values.service.ssh.port }} # 内部通过这个端口访问
      targetPort: {{ .Values.service.ssh.targetPort }} # Docker 暴露出来的接口
    selector:
      app: {{ .Values.name }}